# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestPodsForATF24' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPodsForATF24
  pod 'InputMask', '4.3.0'

end
